### ISSUE TITLE
【Request】FormIDを可変にして欲しい

### ISSUE THREAD

**Issue by fuyutsuki** [fujiwaraizuho/ServerInfoForm#1]
### 問題点
* FormIDの重複
### 改善内容
1. FormIDをconfig.ymlから変更できるようにする
2. FormIDを乱数で生成するようにする
例)
```php
$rand = mt_rand(PHP_INT_MIN, PHP_INT_MAX);
```

**Comment by fujiwaraizuho** [comment]
承知しました。
今日中に乱数での生成に書き換えさせていただきますm(*_ _)m
